import { useMemo } from 'react'
import { collection, query, orderBy } from 'firebase/firestore'
import { FiDollarSign, FiLayers, FiUserCheck, FiUsers } from 'react-icons/fi'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { db } from '../firebase/config'
import useOwnedCollection from '../hooks/useOwnedCollection'
import StatCard from '../components/StatCard'
import { money, monthNames, formatDate } from '../utils/date'
export default function Dashboard() { const {data:users}=useOwnedCollection('users'); const {data:payments}=useOwnedCollection('payments'); const now=new Date(), month=now.getMonth()+1,year=now.getFullYear(); const current=payments.filter(p=>+p.month===month&&+p.year===year); const paid=current.filter(p=>Number(p.amount)>0); const chart=useMemo(()=>monthNames.map((name,i)=>({name:name.slice(0,3),collection:payments.filter(p=>+p.year===year&&+p.month===i+1).reduce((s,p)=>s+Number(p.amount||0),0)})),[payments,year]); return <div className="page"><div className="page-title"><div><h2>Overview</h2><p>{monthNames[month-1]} {year}</p></div></div><div className="stats"><StatCard label="Total Users" value={users.length} icon={<FiUsers/>}/><StatCard label="Paid This Month" value={paid.length} tone="green" icon={<FiUserCheck/>}/><StatCard label="Pending Users" value={Math.max(0,users.length-paid.length)} tone="orange" icon={<FiLayers/>}/><StatCard label="Month Collection" value={money(paid.reduce((s,p)=>s+Number(p.amount),0))} tone="purple" icon={<FiDollarSign/>}/></div><div className="grid-2"><section className="panel"><h3>Monthly collection</h3><div className="chart"><ResponsiveContainer><BarChart data={chart} margin={{top:8,right:8,left:-18,bottom:0}}><XAxis dataKey="name" interval={0} tick={{fontSize:12}}/><YAxis/><Tooltip formatter={v=>money(v)}/><Bar dataKey="collection" fill="#6366f1" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="panel"><h3>Recent payments</h3>{payments.filter(p=>p.amount>0).sort((a,b)=>(b.paymentDate?.seconds||0)-(a.paymentDate?.seconds||0)).slice(0,6).map(p=><div className="activity" key={p.id}><b>{p.userName || 'User'}</b><span>{money(p.amount)} · {formatDate(p.paymentDate)}</span></div>)}{!payments.length&&<p className="empty">No payments recorded yet.</p>}</section></div></div> }
