import { useMemo, useState } from 'react'
import { addDoc, collection, deleteDoc, doc, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore'
import { FiEdit2, FiPlus, FiSearch, FiTrash2 } from 'react-icons/fi'
import toast from 'react-hot-toast'
import { db } from '../firebase/config'
import useCollection from '../hooks/useCollection'
import Modal from '../components/Modal'
import { formatDate, money } from '../utils/date'

const blank = { name: '', category: '', monthlyBill: '', phone: '', address: '' }

export default function Users() {
  const { data: allUsers } = useCollection(db ? query(collection(db, 'users'), orderBy('name')) : null)
  const users = allUsers.filter(user => user.active !== false)
  const { data: savedCategories, error: categoryError } = useCollection(db ? collection(db, 'categories') : null)
  const [search, setSearch] = useState(''); const [form, setForm] = useState(null); const [category, setCategory] = useState(false); const [newCategories, setNewCategories] = useState([])
  const categories = useMemo(() => [...savedCategories, ...newCategories.filter(newItem => !savedCategories.some(saved => saved.id === newItem.id))].filter(item => item.name).sort((a, b) => a.name.localeCompare(b.name)), [savedCategories, newCategories])
  const list = useMemo(() => users.filter(user => [user.name, user.category, user.phone].some(value => String(value || '').toLowerCase().includes(search.toLowerCase()))), [users, search])
  const save = async event => { event.preventDefault(); try { const data = { name: form.name.trim(), category: form.category, monthlyBill: Number(form.monthlyBill || 0), phone: form.phone.trim(), address: form.address.trim(), ...(form.id ? {} : { active: true, createdAt: serverTimestamp() }) }; if (form.id) await updateDoc(doc(db, 'users', form.id), data); else await addDoc(collection(db, 'users'), data); toast.success('User saved'); setForm(null) } catch (error) { toast.error(error.message) } }
  const remove = async id => { if (confirm('Delete this user? Their past payment records will be kept.')) { await updateDoc(doc(db, 'users', id), { active: false, disconnectedAt: serverTimestamp() }); toast.success('User deleted; payment history kept') } }
  return <div className="page"><div className="page-title"><div><h2>Users</h2><p>{users.length} registered customers</p></div><button className="primary" onClick={() => setForm(blank)}><FiPlus /> Add user</button></div><div className="toolbar"><label className="search"><FiSearch /><input placeholder="Search name, category, or phone" value={search} onChange={e => setSearch(e.target.value)} /></label></div><section className="panel table-wrap"><table><thead><tr><th>SL</th><th>Name</th><th>Category</th><th>Monthly Bill</th><th>Phone</th><th>Created</th><th /></tr></thead><tbody>{list.map((user, i) => <tr key={user.id}><td>{i + 1}</td><td><b>{user.name}</b></td><td><span className="tag">{user.category}</span></td><td>{money(user.monthlyBill)}</td><td>{user.phone || '—'}</td><td>{formatDate(user.createdAt)}</td><td className="actions"><button onClick={() => setForm(user)}><FiEdit2 /></button><button className="danger" onClick={() => remove(user.id)}><FiTrash2 /></button></td></tr>)}</tbody></table>{!list.length && <p className="empty">No users match your search.</p>}</section>{form && <Modal title={form.id ? 'Edit user' : 'Add user'} onClose={() => setForm(null)}><UserForm form={form} setForm={setForm} categories={categories} categoryError={categoryError} onCategory={() => setCategory(true)} onSubmit={save} /></Modal>}{category && <CategoryModal categories={categories} users={users} close={() => setCategory(false)} onAdded={item => { setNewCategories(current => [...current, item]); setForm(current => ({ ...current, category: item.name })) }} onRemoved={id => setNewCategories(current => current.filter(item => item.id !== id))} />}</div>
}

function UserForm({ form, setForm, categories, categoryError, onCategory, onSubmit }) { const set = (key, value) => setForm({ ...form, [key]: value }); return <form onSubmit={onSubmit} className="form"><label>Name<input required value={form.name || ''} onChange={e => set('name', e.target.value)} /></label><label>Category<div className="row"><select required value={form.category || ''} onChange={e => set('category', e.target.value)}><option value="">Select category</option>{categories.map(category => <option key={category.id} value={category.name}>{category.name}</option>)}</select><button type="button" className="secondary" onClick={onCategory}>+ New</button></div>{categoryError && <small className="field-error">Categories could not load: {categoryError.code || categoryError.message}</small>}</label><label>Monthly bill<input type="number" min="0" step="any" placeholder="e.g. 500" value={form.monthlyBill ?? ''} onChange={e => set('monthlyBill', e.target.value)} /></label><label>Phone number<input type="tel" inputMode="tel" placeholder="e.g. +8801XXXXXXXXX" value={form.phone || ''} onChange={e => set('phone', e.target.value)} /></label><label>Address<textarea value={form.address || ''} onChange={e => set('address', e.target.value)} /></label><button className="primary">Save user</button></form> }

function CategoryModal({ categories, users, close, onAdded, onRemoved }) { const [name, setName] = useState(''); const save = async event => { event.preventDefault(); const clean = name.trim(); if (!clean) return; if (categories.some(category => category.name.trim().toLowerCase() === clean.toLowerCase())) { toast.error(`The category “${clean}” already exists`); return } try { const added = await addDoc(collection(db, 'categories'), { name: clean, createdAt: serverTimestamp() }); onAdded({ id: added.id, name: clean }); toast.success(`${clean} category added`); setName('') } catch (error) { toast.error(`Could not add category: ${error.message}`) } }; const remove = async category => { const inUse = users.some(user => user.category?.trim().toLowerCase() === category.name.trim().toLowerCase()); if (inUse) return toast.error('This category is used by a customer and cannot be removed'); if (!confirm(`Remove the category “${category.name}”?`)) return; try { await deleteDoc(doc(db, 'categories', category.id)); onRemoved(category.id); toast.success(`${category.name} category removed`) } catch (error) { toast.error(`Could not remove category: ${error.message}`) } }; return <Modal title="Manage categories" onClose={close}><form className="form" onSubmit={save}><label>New category name<input autoFocus required value={name} onChange={e => setName(e.target.value)} /></label><button className="primary">Save category</button></form>{categories.length > 0 && <div className="category-list">{categories.map(category => { const inUse = users.some(user => user.category?.trim().toLowerCase() === category.name.trim().toLowerCase()); return <div className="activity" key={category.id}><b>{category.name}</b><div className="actions"><button className="danger" type="button" title={inUse ? 'This category is in use' : 'Remove category'} disabled={inUse} onClick={() => remove(category)}><FiTrash2 /></button></div></div> })}</div>}</Modal> }
