import { useMemo, useState } from 'react'
import { addDoc, collection, deleteDoc, doc, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore'
import { FiEdit2, FiPlus, FiSearch, FiTrash2 } from 'react-icons/fi'
import toast from 'react-hot-toast'
import { db } from '../firebase/config'
import useCollection from '../hooks/useCollection'
import Modal from '../components/Modal'
import { formatDate } from '../utils/date'
const blank = { name: '', category: '', phone: '', address: '' }
export default function Users() {
  const { data: users } = useCollection(db ? query(collection(db, 'users'), orderBy('name')) : null)
  const { data: savedCategories, error: categoryError } = useCollection(db ? collection(db, 'categories') : null)
  const [search, setSearch] = useState(''); const [form, setForm] = useState(null); const [category, setCategory] = useState(false); const [newCategories, setNewCategories] = useState([])
  const categories = useMemo(() => [...savedCategories, ...newCategories.filter(newItem => !savedCategories.some(saved => saved.id === newItem.id))].filter(c => c.name).sort((a, b) => a.name.localeCompare(b.name)), [savedCategories, newCategories])
  const list = useMemo(() => users.filter(u => [u.name, u.category, u.phone].some(v => String(v || '').toLowerCase().includes(search.toLowerCase()))), [users, search])
  const save = async e => { e.preventDefault(); try { const data = { name: form.name.trim(), category: form.category, phone: form.phone, address: form.address, ...(form.id ? {} : { createdAt: serverTimestamp() }) }; if (form.id) await updateDoc(doc(db, 'users', form.id), data); else await addDoc(collection(db, 'users'), data); toast.success('User saved'); setForm(null) } catch (e) { toast.error(e.message) } }
  const remove = async id => { if (confirm('Delete this user?')) { await deleteDoc(doc(db, 'users', id)); toast.success('User deleted') } }
  return <div className="page"><div className="page-title"><div><h2>Users</h2><p>{users.length} registered customers</p></div><button className="primary" onClick={() => setForm(blank)}><FiPlus /> Add user</button></div><div className="toolbar"><label className="search"><FiSearch /><input placeholder="Search name, category, or phone" value={search} onChange={e => setSearch(e.target.value)} /></label></div><section className="panel table-wrap"><table><thead><tr><th>SL</th><th>Name</th><th>Category</th><th>Phone</th><th>Created</th><th /></tr></thead><tbody>{list.map((u, i) => <tr key={u.id}><td>{i + 1}</td><td data-label="Name"><b>{u.name}</b></td><td data-label="Category"><span className="tag">{u.category}</span></td><td data-label="Phone">{u.phone || '—'}</td><td>{formatDate(u.createdAt)}</td><td className="actions"><button onClick={() => setForm(u)}><FiEdit2 /></button><button className="danger" onClick={() => remove(u.id)}><FiTrash2 /></button></td></tr>)}</tbody></table>{!list.length && <p className="empty">No users match your search.</p>}</section>{form && <Modal title={form.id ? 'Edit user' : 'Add user'} onClose={() => setForm(null)}><UserForm form={form} setForm={setForm} categories={categories} categoryError={categoryError} onCategory={() => setCategory(true)} onSubmit={save} /></Modal>}{category && <CategoryModal categories={categories} close={() => setCategory(false)} onAdded={item => { setNewCategories(current => [...current, item]); setForm(current => ({ ...current, category: item.name })) }} />}</div>
}
function UserForm({ form, setForm, categories, categoryError, onCategory, onSubmit }) { const set = (k, v) => setForm({ ...form, [k]: v }); return <form onSubmit={onSubmit} className="form"><label>Name<input required value={form.name || ''} onChange={e => set('name', e.target.value)} /></label><label>Category<div className="row"><select required value={form.category || ''} onChange={e => set('category', e.target.value)}><option value="">Select category</option>{categories.map(c => <option key={c.id} value={c.name}>{c.name}</option>)}</select><button type="button" className="secondary" onClick={onCategory}>+ New</button></div>{categoryError && <small className="field-error">Categories could not load: {categoryError.code || categoryError.message}</small>}</label><label>Phone number<input value={form.phone || ''} onChange={e => set('phone', e.target.value)} /></label><label>Address<textarea value={form.address || ''} onChange={e => set('address', e.target.value)} /></label><button className="primary">Save user</button></form> }
function CategoryModal({ categories, close, onAdded }) { const [name, setName] = useState(''); const save = async e => { e.preventDefault(); const clean = name.trim(); if (!clean) return; if (categories.some(category => category.name.trim().toLowerCase() === clean.toLowerCase())) { toast.error(`The category “${clean}” already exists`); return } try { const added = await addDoc(collection(db, 'categories'), { name: clean, createdAt: serverTimestamp() }); onAdded({ id: added.id, name: clean }); toast.success(`${clean} category added`); close() } catch (e) { toast.error(`Could not add category: ${e.message}`) } }; return <Modal title="Add new category" onClose={close}><form className="form" onSubmit={save}><label>Category name<input autoFocus required value={name} onChange={e => setName(e.target.value)} /></label><button className="primary">Save category</button></form></Modal> }
