import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export function exportExcel(rows, fileName) {
  const sheet = XLSX.utils.json_to_sheet(rows);

  const book = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(book, sheet, "Report");

  XLSX.writeFile(book, `${fileName}.xlsx`);
}

export function exportCsv(rows, fileName) {
  if (!rows || !rows.length) return;

  const keys = Object.keys(rows[0]);
  const csv = [
    keys.join(","),
    ...rows.map((row) =>
      keys
        .map((key) => {
          const value = row[key] == null ? "" : String(row[key]);
          const escaped = value.replace(/"/g, '""');
          return `"${escaped}"`;
        })
        .join(","),
    ),
  ].join("\r\n");

  const blob = new Blob(["\uFEFF", csv], {
    type: "text/csv;charset=utf-8;",
  });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${fileName}.csv`;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

export function exportPdf(rows, title = "Report") {
  const pdf = new jsPDF("p", "mm", "a4");

  pdf.setFontSize(20);
  pdf.setTextColor(33, 37, 41);
  pdf.text("BillSheet", 14, 18);

  pdf.setFontSize(11);
  pdf.setTextColor(110);

  pdf.text(title, 14, 25);

  pdf.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    31
  );

  const keys = Object.keys(rows[0] || {});

  autoTable(pdf, {
    startY: 38,

    head: [keys],

    body: rows.map((row) =>
      keys.map((key) => row[key])
    ),

    styles: {
      fontSize: 9,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [248, 249, 252],
    },

    margin: {
      left: 14,
      right: 14,
    },
  });

  const pageCount = pdf.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);

    pdf.setFontSize(9);

    pdf.setTextColor(120);

    pdf.text(
      `Page ${i} of ${pageCount}`,
      180,
      290
    );

    pdf.text(
      "Generated by BillSheet",
      14,
      290
    );
  }

  pdf.save(`${title}.pdf`);
}