import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { money } from "./date";

export function exportExcel(rows, fileName) {
  const sheet = XLSX.utils.json_to_sheet(rows);

  const book = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(book, sheet, "Report");

  XLSX.writeFile(book, `${fileName}.xlsx`);
}

export function exportCsv(rows, fileName) {
  if (!rows || !rows.length) return;

  const keys = Object.keys(rows[0]);
  const csv = [
    keys.join(","),
    ...rows.map((row) =>
      keys
        .map((key) => {
          const value = row[key] == null ? "" : String(row[key]);
          const escaped = value.replace(/"/g, '""');
          return `"${escaped}"`;
        })
        .join(","),
    ),
  ].join("\r\n");

  const blob = new Blob(["\uFEFF", csv], {
    type: "text/csv;charset=utf-8;",
  });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${fileName}.csv`;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

export function exportAnnualCustomerReport({
  businessName = "BillSheet",
  customer,
  year,
  summary,
  history,
}) {
  const pdf = new jsPDF("p", "mm", "a4");
  const pageHeight = pdf.internal.pageSize.getHeight();

  pdf.setFillColor(8, 27, 27);
  pdf.rect(0, 0, 210, 54, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text(businessName, 14, 20);
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text("Annual Customer Report", 14, 30);
  pdf.text(`Year ${year}`, 14, 38);
  pdf.text(`Customer: ${customer?.name || "Customer"}`, 14, 46);

  pdf.setTextColor(42, 51, 56);
  pdf.setFontSize(11);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, 14, 64);

  const summaryRows = [
    ["Previous Due", money(summary.previousDue)],
    ["Annual Bill", money(summary.annualBill)],
    ["Paid This Year", money(summary.paidThisYear)],
    ["Outstanding Balance", money(summary.outstandingBalance)],
    ["Credit Carry Forward", money(summary.creditCarryForward)],
    ["Status", summary.balanceStatus || "Account Settled"],
  ];

  autoTable(pdf, {
    startY: 72,
    head: [["Metric", "Amount"]],
    body: summaryRows,
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [16, 69, 66], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [243, 248, 248] },
    margin: { left: 14, right: 14 },
  });

  const historyRows = history.map((entry) => [
    entry.monthName,
    money(entry.monthlyBill),
    money(entry.paid),
    money(entry.remainingDue),
    entry.paymentDate ? new Date(entry.paymentDate).toLocaleDateString() : "—",
    entry.status,
  ]);

  autoTable(pdf, {
    startY: 120,
    head: [["Month", "Monthly Bill", "Paid", "Remaining Due", "Payment Date", "Status"]],
    body: historyRows,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [16, 69, 66], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 250] },
    margin: { left: 14, right: 14 },
  });

  pdf.setFontSize(9);
  pdf.setTextColor(100);
  pdf.text(
    "Carry Forward will automatically be added to the next year's first bill.",
    14,
    pageHeight - 16,
  );

  pdf.save(
    `annual-customer-report-${year}-${customer?.name || "customer"}.pdf`,
  );
}

export function exportPdf(rows, title = "Report") {
  const pdf = new jsPDF("p", "mm", "a4");

  pdf.setFontSize(20);
  pdf.setTextColor(33, 37, 41);
  pdf.text("BillSheet", 14, 18);

  pdf.setFontSize(11);
  pdf.setTextColor(110);

  pdf.text(title, 14, 25);

  pdf.text(`Generated: ${new Date().toLocaleString()}`, 14, 31);

  const keys = Object.keys(rows[0] || {});

  autoTable(pdf, {
    startY: 38,

    head: [keys],

    body: rows.map((row) => keys.map((key) => row[key])),

    styles: {
      fontSize: 9,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [248, 249, 252],
    },

    margin: {
      left: 14,
      right: 14,
    },
  });

  const pageCount = pdf.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);

    pdf.setFontSize(9);

    pdf.setTextColor(120);

    pdf.text(`Page ${i} of ${pageCount}`, 180, 290);

    pdf.text("Generated by BillSheet", 14, 290);
  }

  pdf.save(`${title}.pdf`);
}
