
export function exportExcel(rows, fileName) {
  const sheet = XLSX.utils.json_to_sheet(rows);

  const book = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(book, sheet, "Report");

  XLSX.writeFile(book, `${fileName}.xlsx`);
}

export function exportCsv(rows, fileName) {
  if (!rows || !rows.length) return;

  const keys = Object.keys(rows[0]);
  const csv = [
    keys.join(","),
    ...rows.map((row) =>
      keys
        .map((key) => {
          const value = row[key] == null ? "" : String(row[key]);
          const escaped = value.replace(/"/g, '""');
          return `"${escaped}"`;
        })
        .join(","),
    ),
  ].join("\r\n");

  const blob = new Blob(["\uFEFF", csv], {
    type: "text/csv;charset=utf-8;",
  });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${fileName}.csv`;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

const formatAmountForExport = (
  value,
  { isDue = false, isAdvance = false } = {},
) => {
  const numeric = Number(value || 0);
  if (!Number.isFinite(numeric)) return money(0);
  if (numeric === 0) return money(0);
  if (isDue)
    return formatBalanceDisplayValue({
      due: Math.abs(numeric),
      carryForward: 0,
    });
  if (isAdvance)
    return formatBalanceDisplayValue({
      due: 0,
      carryForward: Math.abs(numeric),
    });
  return money(numeric);
};

export function exportPdf(rows, title = "Report", summary = {}) {
  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Header
  pdf.setFillColor(18, 52, 86);
  pdf.rect(0, 0, pageWidth, 34, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("Bill Sheet", 15, 15);

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  pdf.text("Monthly Collection Report", 15, 24);

  // Report information
  pdf.setTextColor(40);
  pdf.setFontSize(11);

  pdf.text(`Report : ${title}`, 15, 45);
  pdf.text(`Generated : ${new Date().toLocaleString()}`, 15, 52);

  // Table
  autoTable(pdf, {
    startY: 60,

    head: [Object.keys(rows[0] || {})],

    body: rows.map((row) => Object.values(row)),

    styles: {
      fontSize: 9,
      cellPadding: 3,
      valign: "middle",
    },

    headStyles: {
      fillColor: [25, 84, 140],
      textColor: 255,
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [245, 248, 252],
    },

    margin: {
      left: 15,
      right: 15,
    },
  });

  const finalY = pdf.lastAutoTable.finalY + 10;

  pdf.setDrawColor(200);
  pdf.roundedRect(15, finalY, 180, 42, 2, 2);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.text("Summary", 20, finalY + 8);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  pdf.text(`Total Users : ${summary.totalUsers ?? "-"}`, 20, finalY + 16);
  pdf.text(`Paid Users : ${summary.paidUsers ?? "-"}`, 20, finalY + 23);
  pdf.text(`Pending Users : ${summary.pendingUsers ?? "-"}`, 20, finalY + 30);

  pdf.text(`Total Bill : ${summary.totalBill ?? "-"}`, 110, finalY + 16);
  pdf.text(`Collection : ${summary.totalCollection ?? "-"}`, 110, finalY + 23);
  pdf.text(`Total Due : ${summary.totalDue ?? "-"}`, 110, finalY + 30);

  pdf.setFontSize(10);
  pdf.setTextColor(100);

  pdf.text("Generated by Bill Sheet", 15, pageHeight - 12);

  pdf.setFontSize(10);
  pdf.setTextColor(100);

  pdf.text(`Total Customers : ${rows.length}`, 15, finalY);

  pdf.text("Generated by Bill Sheet", 15, pageHeight - 12);

  const pages = pdf.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    pdf.setPage(i);

    pdf.setFontSize(9);

    pdf.text(`Page ${i} of ${pages}`, pageWidth - 35, pageHeight - 12);
  }

  pdf.save(`${title}.pdf`);
}
